### ISSUE TITLE
plugin import not working please help

### ISSUE THREAD

**Issue by retr0-arch** [Aytackydln/Artemis.Plugins.Devices.Bloody#1]
WRN] [Artemis.Core.Services.PluginManagementService] Plugin change detected, but could not find plugin. C:\ProgramData\Artemis\Plugins\Artemis.Plugins.Devices.Bloody-9aafb8e4\plugin.json

**Comment by Aytackydln** [comment]
It's been a while since I changed this. I don't have a bloody device right now so it may not work. And, this currently only supports few select mice and mousepads

Please try this zip, then I will push my changes to repository and make release
[Artemis.Plugins.Devices.Bloody-9aafb8e4.zip](https://github.com/Aytackydln/Artemis.Plugins.Devices.Bloody/files/12432682/Artemis.Plugins.Devices.Bloody-9aafb8e4.zip)

**Comment by retr0-arch** [comment]
the import happened but the mouse w60 max was not found, I restarted the plugin and got the following error: - Artemis.Plugins.Devices.Bloody v0.0.1.0 - 9aafb8e4-5af7-44c4-ae98-ace94103c27f' failed to enable.
System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'RGB.NET.Devices.Bloody.BloodyDeviceFactory'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RGB.NET.Devices.Bloody.BloodyDeviceFactory'.
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)
   at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\RgbService.cs:line 201
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 174
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 762

**Comment by retr0-arch** [comment]
I don't really know, but maybe I can help?

**Comment by retr0-arch** [comment]
I don't really know much about this, but maybe I can help?

**Comment by Aytackydln** [comment]
I don't know about that error when the plugin is restarted but I've added W60 Max device Id

[Artemis.Plugins.Devices.Bloody-9aafb8e4.zip](https://github.com/Aytackydln/Artemis.Plugins.Devices.Bloody/files/12437705/Artemis.Plugins.Devices.Bloody-9aafb8e4.zip)

**Comment by retr0-arch** [comment]
2023-08-25 21:04:26.196 [WRN] [Artemis.Core.Services.PluginManagementService] Plugin feature 'Artemis.Plugins.Devices.Bloody.BloodyDeviceProvider - Artemis.Plugins.Devices.Bloody v0.0.2.0 - 9aafb8e4-5af7-44c4-ae98-ace94103c27f' failed to enable.
System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'RGB.NET.Devices.Bloody.BloodyDeviceFactory'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RGB.NET.Devices.Bloody.BloodyDeviceFactory'.
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)
   at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\RgbService.cs:line 201
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 174
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 762

**Comment by Aytackydln** [comment]
Did you restart Artemis?

**Comment by retr0-arch** [comment]
yes

**Comment by retr0-arch** [comment]
after another reboot, it activated without error, but the device does not find

**Comment by Aytackydln** [comment]
can you tell me your mouse's PID ?

**Comment by retr0-arch** [comment]
PID:527A

**Comment by Aytackydln** [comment]
Alright, hopefully this will work

[Artemis.Plugins.Devices.Bloody-9aafb8e4.zip](https://github.com/Aytackydln/Artemis.Plugins.Devices.Bloody/files/12441611/Artemis.Plugins.Devices.Bloody-9aafb8e4.zip)

**Comment by retr0-arch** [comment]
still not working maybe due to an error that appears when I turn it off and on again

**Comment by Aytackydln** [comment]
Does it work after restarting Artemis?

I'm sorry there are some problems with the design of rgb.net and I can't figure out why it doesn't work after restarting plugin.

**Comment by Aytackydln** [comment]
Finally managed to fix restarting issue, but I'm not sure it will still work with your device

[Artemis.Plugins.Devices.Bloody.zip](https://github.com/Aytackydln/Artemis.Plugins.Devices.Bloody/files/12502108/Artemis.Plugins.Devices.Bloody.zip)

**Comment by retr0-arch** [comment]
it worked, the mouse appeared, of course, in the form of a strip

**Comment by Aytackydln** [comment]
[w60.zip](https://github.com/Aytackydln/Artemis.Plugins.Devices.Bloody/files/12548399/w60.zip)


You can use the layout I created

**Comment by Aytackydln** [comment]
Sorry, just realized upload was wrong. Reuploaded on previous comment

**Comment by retr0-arch** [comment]
now everything works fine, of course, the speed of the update is small, but this is already a problem with the mouse, I hope for the development of the plugin and thanks

**Comment by Aytackydln** [comment]
that's intentional because increasing the updates reduces responsiveness of the mouse
